spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    include: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}
server:
  port: 8888
