version: '2.1'

services:
  topic-service-database:
    container_name: topic-service-database
    image: postgres:11.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=${TOPIC_SERVICE_DATABASE_PASSWORD}
      - POSTGRES_USER=${TOPIC_SERVICE_DATABASE_USER}
      - POSTGRES_DB=${TOPIC_SERVICE_DATABASE}
    ports:
      - ${TOPIC_SERVICE_DATABASE_PORT}:5432
    volumes:
      - ts-db:/var/lib/postgresql/topic-service-database/data
    networks:
      - information-center-prod-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${TOPIC_SERVICE_DATABASE} -U ${TOPIC_SERVICE_DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  topic-service:
      build:
        context: ./topic-service
      networks:
        - information-center-prod-network
      ports:
        - 8881:8080
      environment:
        - TOPIC_SERVICE_DATABASE
        - TOPIC_SERVICE_DATABASE_USER
        - TOPIC_SERVICE_DATABASE_PASSWORD
        - TOPIC_SERVICE_DATABASE_PORT=5432
        - TOPIC_SERVICE_DATABASE_HOST=topic-service-database
      depends_on:
        topic-service-database:
          condition: service_healthy
      links:
        - topic-service-database


  question-service-database:
    container_name: question-service-database
    image: postgres:11.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=${QUESTION_SERVICE_DATABASE_PASSWORD}
      - POSTGRES_USER=${QUESTION_SERVICE_DATABASE_USER}
      - POSTGRES_DB=${QUESTION_SERVICE_DATABASE}
    ports:
      - 5442:5432
    volumes:
      - qs-db:/var/lib/postgresql/question-service-database/data
    networks:
      - information-center-prod-network

  account-service-database:
    container_name: account-service-database
    image: postgres:11.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=${ACCOUNT_SERVICE_DATABASE_PASSWORD}
      - POSTGRES_USER=${ACCOUNT_SERVICE_DATABASE_USER}
      - POSTGRES_DB=${ACCOUNT_SERVICE_DATABASE}
    ports:
      - 5443:5432
    volumes:
      - acs-db:/var/lib/postgresql/account-service-database/data
    networks:
      - information-center-prod-network

  auth-service-database:
    container_name: auth-service-database
    image: postgres:11.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=${AUTH_SERVICE_DATABASE_PASSWORD}
      - POSTGRES_USER=${AUTH_SERVICE_DATABASE_USER}
      - POSTGRES_DB=${AUTH_SERVICE_DATABASE}
    ports:
      - 5444:5432
    volumes:
      - aus-db:/var/lib/postgresql/auth-service-database/data
    networks:
      - information-center-prod-network


volumes:
  ts-db:
  qs-db:
  acs-db:
  aus-db:
networks:
  information-center-prod-network:
