version: '2.1'

services:
  topic-service-database:
    container_name: topic-service-database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${TOPIC_SERVICE_DATABASE}
      MYSQL_USER: ${TOPIC_SERVICE_USER}
      MYSQL_PASSWORD: ${TOPIC_SERVICE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TOPIC_SERVICE-ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3301:3306
    volumes:
      - ts-db:/mysql/var/lib/topic-service-database/data

  question-service-database:
    container_name: question-service-database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${QUESTION_SERVICE_DATABASE}
      MYSQL_USER: ${QUESTION_SERVICE_USER}
      MYSQL_PASSWORD: ${QUESTION_SERVICE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${QUESTION_SERVICE_ROOT_PASSWORD}
    ports:
      - 3302:3306
    volumes:
      - qs-db:/mysql/var/lib/question-service-database/data

  account-service-database:
    container_name: account-service-database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${ACCOUNT_SERVICE_DATABASE}
      MYSQL_USER: ${ACCOUNT_SERVICE_USER}
      MYSQL_PASSWORD: ${ACCOUNT_SERVICE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ACCOUNT_SERVICE_ROOT_PASSWORD}
    ports:
      - 3303:3306
    volumes:
      - acs-db:/mysql/var/lib/account-service-database/data

  auth-service-database:
    container_name: auth-service-database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${AUTH_SERVICE_DATABASE}
      MYSQL_USER: ${AUTH_SERVICE_USER}
      MYSQL_PASSWORD: ${AUTH_SERVICE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTH_SERVICE_ROOT_PASSWORD}
    ports:
      - 3304:3306
    volumes:
      - aus-db:/mysql/var/lib/auth-service-database/data

volumes:
  ts-db:
  qs-db:
  acs-db:
  aus-db: