version: '2.1'

services:
  course-service-database:
    container_name: course-service-database
    extends:
      file: docker-compose.yaml
      service: course-service-database

  quiz-service-database:
    container_name: quiz-service-database
    extends:
      file: docker-compose.yaml
      service: quiz-service-database

  account-service-database:
    container_name: account-service-database
    extends:
      file: docker-compose.yaml
      service: account-service-database

  auth-service-database:
    container_name: auth-service-database
    extends:
      file: docker-compose.yaml
      service: auth-service-database

  config:
    container_name: config
    extends:
      file: docker-compose.yaml
      service: config

  gateway:
    extends:
      file: docker-compose.yaml
      service: gateway
    container_name: gateway
    depends_on:
      config:
        condition: service_healthy

  monitoring:
    extends:
      file: docker-compose.yaml
      service: monitoring
    container_name: monitoring
    depends_on:
      config:
        condition: service_healthy

  registry:
    extends:
      file: docker-compose.yaml
      service: registry
    container_name: registry
    depends_on:
      config:
        condition: service_healthy

  course-service:
    extends:
      file: docker-compose.yaml
      service: course-service
    container_name: course-service
    depends_on:
      course-service-database:
        condition: service_healthy
      config:
        condition: service_healthy

  quiz-service:
    extends:
      file: docker-compose.yaml
      service: quiz-service
    container_name: quiz-service
    depends_on:
      quiz-service-database:
        condition: service_healthy
      config:
        condition: service_healthy


  account-service:
    extends:
      file: docker-compose.yaml
      service: account-service
    container_name: account-service
    depends_on:
      account-service-database:
        condition: service_healthy
      config:
        condition: service_healthy

  auth-service:
    extends:
      file: docker-compose.yaml
      service: auth-service
    container_name: auth-service
    depends_on:
      auth-service-database:
        condition: service_healthy
      config:
        condition: service_healthy

  email-service:
    extends:
      file: docker-compose.yaml
      service: email-service
    container_name: email-service
    depends_on:
      config:
        condition: service_healthy

  information-center-web:
    extends:
      service: information-center-web
      file: docker-compose.yaml

  rabbitmq:
    extends:
      file: docker-compose.yaml
      service: rabbitmq
    container_name: rabbitmq

volumes:
  vs:
  ts-db:
  qs-db:
  acs-db:
  aus-db:
  vs-db:
networks:
  information-center-prod-network:
