version: '2.1'

services:
  course-service-database:
    container_name: course-service-database
    extends:
      file: docker-compose.yaml
      service: course-service-database
    ports:
      - ${COURSE_SERVICE_DATABASE_PORT}:5432

  quiz-service-database:
    container_name: quiz-service-database
    extends:
      file: docker-compose.yaml
      service: quiz-service-database
    ports:
      - ${QUIZ_SERVICE_DATABASE_PORT}:5432

  account-service-database:
    container_name: account-service-database
    extends:
      file: docker-compose.yaml
      service: account-service-database
    ports:
      - ${ACCOUNT_SERVICE_DATABASE_PORT}:5432

  auth-service-database:
    container_name: auth-service-database
    extends:
      file: docker-compose.yaml
      service: auth-service-database
    ports:
      - ${AUTH_SERVICE_DATABASE_PORT}:5432

  config:
    container_name: config
    extends:
      file: docker-compose.yaml
      service: config
    ports:
      - 8888:8888
    environment:
      - ACCOUNT_SERVICE_PASSWORD

  gateway:
    extends:
      file: docker-compose.yaml
      service: gateway
    container_name: gateway
    depends_on:
      config:
        condition: service_healthy

  monitoring:
    extends:
      file: docker-compose.yaml
      service: monitoring
    container_name: monitoring
    depends_on:
      config:
        condition: service_healthy

  registry:
    extends:
      file: docker-compose.yaml
      service: registry
    container_name: registry
    depends_on:
      config:
        condition: service_healthy

  rabbitmq:
    extends:
      file: docker-compose.yaml
      service: rabbitmq
    container_name: rabbitmq

  account-service:
    extends:
      file: docker-compose.yaml
      service: account-service
    container_name: account-service
    depends_on:
      account-service-database:
        condition: service_healthy
      config:
        condition: service_healthy
    ports:
      - 8883:8883

  auth-service:
    extends:
      file: docker-compose.yaml
      service: auth-service
    container_name: auth-service
    depends_on:
      auth-service-database:
        condition: service_healthy
      config:
        condition: service_healthy
    ports:
      - 8884:8884


volumes:
  vs:
  ts-db:
  qs-db:
  acs-db:
  aus-db:
networks:
  information-center-prod-network:
