#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/information-center
#  jpa:
#    generate-ddl: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#      use-new-id-generator-mappings: false
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#server:
#  port: 8087
