spring:
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB
  #  cloud:
#    stream:
#      kafka:
#        binder:
#         brokers: localhost:9092
#      bindings:
#        greetings-in:
#          destination: add-
#          contentType: application/json
#        greetings-out:
#          destination: greetings
#          contentType: application/json
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/information-center
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
server:
  port: 8088

