spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${ACCOUNT_SERVICE_DATABASE_HOST}:${ACCOUNT_SERVICE_DATABASE_PORT}/${ACCOUNT_SERVICE_DATABASE}?autoReconnect=true&useSSL=false
    username: ${ACCOUNT_SERVICE_DATABASE_USER}
    password: ${ACCOUNT_SERVICE_DATABASE_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.master.yaml