logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_USERNAME}:${REGISTRY_PASSWORD}@${REGISTRY_SERVICE_HOST}:8761/eureka
