logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000

ribbon:
  ReadTimeout: 40000
  connection-timeout: 3000
  eureka:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_USERNAME}:${REGISTRY_PASSWORD}@${REGISTRY_SERVICE_HOST}:8761/eureka

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    httptrace:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - httptrace
          - info
          - loggers
          - metrics
          - prometheus
          - refresh
    enabled-by-default: false

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8884/auth/user/current
