server:
  servlet:
    context-path: /email
  port: 8885

security:
  oauth2:
    client:
      clientId: email-service
      clientSecret: ${EMAIL_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:8884/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
