zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false

    subscription-service:
      path: /subscription/**
      serviceId: account-service
      stripPrefix: false

    account-service:
      path: /accounts/**
      serviceId: account-service
      stripPrefix: false

    topic-service:
      path: /topic/**
      serviceId: topic-service
      stripPrefix: false

    question-service:
      path: /question/**
      serviceId: question-service
      stripPrefix: false

    answer-service:
      path: /answer/**
      serviceId: question-service
      stripPrefix: false

server:
  port: 8880
