zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false

    account-service:
      path: /account/**
      serviceId: account-service
      stripPrefix: false

    topic-service:
      path: /topic-service/**
      serviceId: topic-service
      stripPrefix: false

    question-service:
      path: /question-service/**
      serviceId: question-service
      stripPrefix: false

    email-service:
      path: /email-service/**
      serviceId: email-service
      stripPrefix: false

server:
  port: 8880

