zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false

    account-service:
      path: /account/**
      serviceId: account-service
      stripPrefix: false

    course-service:
      path: /course-service/**
      serviceId: course-service
      stripPrefix: false

    quiz-service:
      path: /quiz/**
      serviceId: quiz-service
      stripPrefix: false

    email-service:
      path: /email-service/**
      serviceId: email-service
      stripPrefix: false

server:
  port: 8880

