spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${TOPIC_SERVICE_DATABASE_HOST}:${TOPIC_SERVICE_DATABASE_PORT}/${TOPIC_SERVICE_DATABASE}?autoReconnect=true&useSSL=false
    username: ${TOPIC_SERVICE_DATABASE_USER}
    password: ${TOPIC_SERVICE_DATABASE_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.master.yaml

server:
  servlet:
    context-path: /topic-service
  port: 8881

security:
  oauth2:
    client:
      clientId: topic-service
      clientSecret: ${TOPIC_SERVICE_PASSWORD}
      accessTokenUri: http://${AUTH_SERVER_HOST:localhost}:8884/auth/oauth/token
      grant-type: client_credentials
      scope: server
